*******************************************************************************************************************************************************
`src/trie/iterator_test.go <https://github.com/Fantom-Foundation/go-lachesis/blob/18d4a6c33a706aa99ed73349c24d20933ae255efsrc/trie/iterator_test.go>`_
*******************************************************************************************************************************************************


.. function:: func TestNodeIteratorCoverage(t *testing.T) [line: 87]

	| Tests that the node iterator indeed walks over the entire database contents.

`View source at line: 87 <https://github.com/Fantom-Foundation/go-lachesis/blob/18d4a6c33a706aa99ed73349c24d20933ae255efsrc/trie/iterator_test.go#L87>`_

.. function:: func TestIteratorContinueAfterErrorDisk(t *testing.T) [line: 288]

	| This test checks that nodeIterator.Next can be retried after inserting missing trie nodes.

`View source at line: 288 <https://github.com/Fantom-Foundation/go-lachesis/blob/18d4a6c33a706aa99ed73349c24d20933ae255efsrc/trie/iterator_test.go#L288>`_

.. function:: func TestIteratorContinueAfterSeekErrorDisk(t *testing.T) [line: 382]

	| Similar to the test above, this one checks that failure to create nodeIterator at a
	| certain key prefix behaves correctly when Next is called. The expectation is that Next
	| should retry seeking before returning true for the first time.

`View source at line: 382 <https://github.com/Fantom-Foundation/go-lachesis/blob/18d4a6c33a706aa99ed73349c24d20933ae255efsrc/trie/iterator_test.go#L382>`_